// This file was automatically @generated by Tungsten.
// It is not intended for manual editing.

declare const images: {
	placeholder: {
		check: string
		x: string
	}
	searchbar: {
		"chevron-down": (dpiScale: number) => string
		search: (dpiScale: number) => string
	}
}

export = images