// This file was automatically @generated by Tungsten.
// It is not intended for manual editing.

declare const images: {
	check: {
		Image: string
		ImageRectOffset: Vector2
		ImageRectSize: Vector2
	}
	"chevron-down": (dpiScale: number) => string
	search: (dpiScale: number) => string
	x: {
		Image: string
		ImageRectOffset: Vector2
		ImageRectSize: Vector2
	}
}

export = images