// This file was automatically @generated by Tungsten.
// It is not intended for manual editing.

declare const images: {
	check: string
	"chevron-down": string
	search: string
	x: string
}

export = images