use anyhow::{Context, Result};
use std::collections::BTreeMap;

// Types
/// Describes what a codegen entry represents, which controls what Luau is emitted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CodegenKind {
    /// A packed spritesheet region — emits the full sprite table.
    Sprite {
        rect_offset: (u32, u32),
        rect_size: (u32, u32),
    },
    /// Any asset that resolves to a plain rbxassetid:// string.
    /// Covers individual images, audio, models, animations.
    Asset,
}

pub struct CodegenEntry {
    pub name: String,
    pub asset_id: u64,
    pub kind: CodegenKind,
}

impl CodegenEntry {
    /// Convenience constructor for a packed sprite entry.
    pub fn sprite(
        name: String,
        asset_id: u64,
        rect_offset: (u32, u32),
        rect_size: (u32, u32),
    ) -> Self {
        Self {
            name,
            asset_id,
            kind: CodegenKind::Sprite {
                rect_offset,
                rect_size,
            },
        }
    }
    /// Convenience constructor for a plain asset entry (image, audio, model, animation).
    pub fn asset(name: String, asset_id: u64) -> Self {
        Self {
            name,
            asset_id,
            kind: CodegenKind::Asset,
        }
    }
}

// Tree (for nested style)
enum TreeNode<'a> {
    Leaf(&'a CodegenEntry),
    Branch(BTreeMap<String, TreeNode<'a>>),
}

// Public API
pub fn generate(
    entries: Vec<CodegenEntry>,
    table_name: &str,
    style: &str,
    strip_extension: bool,
    output_path: &str,
) -> Result<()> {
    let mut lines: Vec<String> = Vec::with_capacity(3 + entries.len() * 5 + 2);

    lines.push("-- This file was automatically @generated by Tungsten.".into());
    lines.push("-- It is not intended for manual editing.".into());
    lines.push(String::new());

    match style {
        "nested" => generate_nested(&entries, strip_extension, &mut lines, table_name),
        _ => generate_flat(&entries, strip_extension, &mut lines, table_name),
    }

    lines.push(String::new());
    lines.push(format!("return {}", table_name));

    if let Some(parent) = std::path::Path::new(output_path).parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory for \"{}\"", output_path))?;
    }

    std::fs::write(output_path, lines.join("\n"))
        .with_context(|| format!("Failed to write codegen output to \"{}\"", output_path))
}

// Key normalisation
/// Strip any file extension from the last path component.
fn strip_ext(name: &str) -> &str {
    if let Some(dot) = name.rfind('.') {
        // Only strip if the dot isn't the very first character
        if dot > 0 { &name[..dot] } else { name }
    } else {
        name
    }
}

fn entry_key<'a>(entry: &'a CodegenEntry, strip_extension: bool) -> &'a str {
    if strip_extension {
        strip_ext(&entry.name)
    } else {
        &entry.name
    }
}

// Value emission
/// Emit the Luau value for a single entry at the given indent depth.
#[allow(dead_code)]
fn emit_value(entry: &CodegenEntry, lines: &mut Vec<String>, indent: usize) {
    let ind = "\t".repeat(indent);
    let ind1 = "\t".repeat(indent + 1);

    match &entry.kind {
        CodegenKind::Sprite {
            rect_offset,
            rect_size,
        } => {
            lines.push(format!("{}{{", ind));
            lines.push(format!(
                "{}Image = \"rbxassetid://{}\",",
                ind1, entry.asset_id
            ));
            lines.push(format!(
                "{}ImageRectOffset = Vector2.new({}, {}),",
                ind1, rect_offset.0, rect_offset.1
            ));
            lines.push(format!(
                "{}ImageRectSize = Vector2.new({}, {}),",
                ind1, rect_size.0, rect_size.1
            ));
            lines.push(format!("{}}}", ind));
        }
        CodegenKind::Asset => {
            lines.push(format!("{}\"rbxassetid://{}\"", ind, entry.asset_id));
        }
    }
}

// Flat style
fn generate_flat(
    entries: &[CodegenEntry],
    strip_extension: bool,
    lines: &mut Vec<String>,
    table_name: &str,
) {
    lines.push(format!("local {} = {{", table_name));

    for entry in entries {
        let key = entry_key(entry, strip_extension);
        let quoted_key = luau_key(key);

        match &entry.kind {
            CodegenKind::Sprite {
                rect_offset,
                rect_size,
            } => {
                lines.push(format!("\t{} = {{", quoted_key));
                lines.push(format!("\t\tImage = \"rbxassetid://{}\",", entry.asset_id));
                lines.push(format!(
                    "\t\tImageRectOffset = Vector2.new({}, {}),",
                    rect_offset.0, rect_offset.1
                ));
                lines.push(format!(
                    "\t\tImageRectSize = Vector2.new({}, {}),",
                    rect_size.0, rect_size.1
                ));
                lines.push("\t},".into());
            }
            CodegenKind::Asset => {
                lines.push(format!(
                    "\t{} = \"rbxassetid://{}\",",
                    quoted_key, entry.asset_id
                ));
            }
        }
    }

    lines.push("}".into());
}

// Nested style
fn build_tree<'a>(
    entries: &'a [CodegenEntry],
    strip_extension: bool,
) -> BTreeMap<String, TreeNode<'a>> {
    let mut root: BTreeMap<String, TreeNode<'a>> = BTreeMap::new();

    for entry in entries {
        let key = entry_key(entry, strip_extension);
        let parts: Vec<&str> = key.split('/').collect();
        let mut current = &mut root;

        for (i, &part) in parts.iter().enumerate() {
            if i == parts.len() - 1 {
                current.insert(part.to_string(), TreeNode::Leaf(entry));
            } else {
                current = match current
                    .entry(part.to_string())
                    .or_insert_with(|| TreeNode::Branch(BTreeMap::new()))
                {
                    TreeNode::Branch(map) => map,
                    TreeNode::Leaf(_) => break, // path collision — skip
                };
            }
        }
    }

    root
}

fn write_tree(tree: &BTreeMap<String, TreeNode>, lines: &mut Vec<String>, depth: usize) {
    let indent = "\t".repeat(depth);

    for (key, node) in tree {
        let quoted_key = luau_key(key);
        match node {
            TreeNode::Leaf(entry) => {
                match &entry.kind {
                    CodegenKind::Sprite {
                        rect_offset,
                        rect_size,
                    } => {
                        let ind1 = "\t".repeat(depth + 1);
                        lines.push(format!("{}{} = {{", indent, quoted_key));
                        lines.push(format!(
                            "{}Image = \"rbxassetid://{}\",",
                            ind1, entry.asset_id
                        ));
                        lines.push(format!(
                            "{}ImageRectOffset = Vector2.new({}, {}),",
                            ind1, rect_offset.0, rect_offset.1
                        ));
                        lines.push(format!(
                            "{}ImageRectSize = Vector2.new({}, {}),",
                            ind1, rect_size.0, rect_size.1
                        ));
                        lines.push(format!("{}}},", indent));
                    }
                    CodegenKind::Asset => {
                        lines.push(format!(
                            "{}{} = \"rbxassetid://{}\"",
                            indent, quoted_key, entry.asset_id
                        ));
                        // Trailing comma on separate push so the pattern is uniform.
                        let last = lines.last_mut().unwrap();
                        last.push(',');
                    }
                }
            }
            TreeNode::Branch(subtree) => {
                lines.push(format!("{}{} = {{", indent, quoted_key));
                write_tree(subtree, lines, depth + 1);
                lines.push(format!("{}}},", indent));
            }
        }
    }
}

fn generate_nested(
    entries: &[CodegenEntry],
    strip_extension: bool,
    lines: &mut Vec<String>,
    table_name: &str,
) {
    let tree = build_tree(entries, strip_extension);
    lines.push(format!("local {} = {{", table_name));
    write_tree(&tree, lines, 1);
    lines.push("}".into());
}

// Luau key quoting

/// Returns the key in the correct Luau table syntax.
/// Valid identifiers are used bare; anything else gets ["quoted"].
fn luau_key(key: &str) -> String {
    if is_valid_identifier(key) {
        key.to_string()
    } else {
        format!("[\"{}\"]", key)
    }
}

fn is_valid_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;

    fn sprite_entries() -> Vec<CodegenEntry> {
        vec![
            CodegenEntry::sprite("48/arrow-up.png".into(), 12345678, (0, 0), (48, 48)),
            CodegenEntry::sprite("48/arrow-down.png".into(), 12345678, (48, 0), (48, 48)),
            CodegenEntry::sprite("256/arrow-up.png".into(), 87654321, (0, 0), (256, 256)),
        ]
    }

    fn mixed_entries() -> Vec<CodegenEntry> {
        vec![
            CodegenEntry::sprite("icons/arrow.png".into(), 111, (0, 0), (48, 48)),
            CodegenEntry::asset("sounds/click.mp3".into(), 222),
            CodegenEntry::asset("models/sword.rbxm".into(), 333),
            CodegenEntry::asset("backgrounds/menu.png".into(), 444),
        ]
    }

    // Sprite-only (backwards compat)
    #[test]
    fn test_nested_has_subfolders_as_keys() {
        generate(
            sprite_entries(),
            "Icons",
            "nested",
            true,
            "test_nested.luau",
        )
        .unwrap();
        let content = std::fs::read_to_string("test_nested.luau").unwrap();
        assert!(content.contains("[\"48\"]"));
        assert!(content.contains("[\"256\"]"));
        assert!(content.contains("arrow-up"));
        std::fs::remove_file("test_nested.luau").unwrap();
    }

    #[test]
    fn test_flat_contains_asset_ids() {
        generate(sprite_entries(), "Icons", "flat", false, "test_flat.luau").unwrap();
        let content = std::fs::read_to_string("test_flat.luau").unwrap();
        assert!(content.contains("rbxassetid://12345678"));
        assert!(content.contains("rbxassetid://87654321"));
        std::fs::remove_file("test_flat.luau").unwrap();
    }

    #[test]
    fn test_strip_extension() {
        generate(sprite_entries(), "Icons", "flat", true, "test_strip.luau").unwrap();
        let content = std::fs::read_to_string("test_strip.luau").unwrap();
        assert!(content.contains("arrow-up"));
        assert!(!content.contains("arrow-up.png"));
        std::fs::remove_file("test_strip.luau").unwrap();
    }

    // Mixed asset types
    #[test]
    fn test_flat_mixed_assets() {
        generate(
            mixed_entries(),
            "Assets",
            "flat",
            true,
            "test_mixed_flat.luau",
        )
        .unwrap();
        let content = std::fs::read_to_string("test_mixed_flat.luau").unwrap();
        // Sprite should have full table
        assert!(content.contains("Image = \"rbxassetid://111\""));
        assert!(content.contains("ImageRectOffset"));
        assert!(content.contains("ImageRectSize"));
        // Plain assets should be bare strings
        assert!(content.contains("= \"rbxassetid://222\""));
        assert!(content.contains("= \"rbxassetid://333\""));
        assert!(content.contains("= \"rbxassetid://444\""));
        // Plain assets should NOT have sprite table fields
        assert!(!content.contains("ImageRectOffset = Vector2.new(0, 0),\n\tclick"));
        std::fs::remove_file("test_mixed_flat.luau").unwrap();
    }

    #[test]
    fn test_nested_mixed_assets() {
        generate(
            mixed_entries(),
            "Assets",
            "nested",
            true,
            "test_mixed_nested.luau",
        )
        .unwrap();
        let content = std::fs::read_to_string("test_mixed_nested.luau").unwrap();
        assert!(content.contains("icons"));
        assert!(content.contains("sounds"));
        assert!(content.contains("models"));
        assert!(content.contains("Image = \"rbxassetid://111\""));
        assert!(content.contains("\"rbxassetid://222\""));
        assert!(content.contains("\"rbxassetid://333\""));
        std::fs::remove_file("test_mixed_nested.luau").unwrap();
    }

    #[test]
    fn test_asset_only_no_sprite_fields() {
        let entries = vec![
            CodegenEntry::asset("click.mp3".into(), 999),
            CodegenEntry::asset("boom.ogg".into(), 888),
        ];
        generate(entries, "Sounds", "flat", true, "test_sounds.luau").unwrap();
        let content = std::fs::read_to_string("test_sounds.luau").unwrap();
        assert!(content.contains("\"rbxassetid://999\""));
        assert!(content.contains("\"rbxassetid://888\""));
        assert!(!content.contains("ImageRectOffset"));
        assert!(!content.contains("Image ="));
        std::fs::remove_file("test_sounds.luau").unwrap();
    }

    // Key quoting

    #[test]
    fn test_valid_identifier_used_bare() {
        assert_eq!(luau_key("arrow"), "arrow");
        assert_eq!(luau_key("_private"), "_private");
        assert_eq!(luau_key("arrow48"), "arrow48");
    }

    #[test]
    fn test_invalid_identifier_gets_quoted() {
        assert_eq!(luau_key("arrow-up"), "[\"arrow-up\"]");
        assert_eq!(luau_key("48px"), "[\"48px\"]");
        assert_eq!(luau_key("my icon"), "[\"my icon\"]");
    }

    // strip_ext

    #[test]
    fn test_strip_ext_removes_any_extension() {
        assert_eq!(strip_ext("icon.png"), "icon");
        assert_eq!(strip_ext("sound.mp3"), "sound");
        assert_eq!(strip_ext("model.rbxm"), "model");
        assert_eq!(strip_ext("no_ext"), "no_ext");
        assert_eq!(strip_ext(".hidden"), ".hidden"); // leading dot preserved
    }
}
