use anyhow::{Context, Result};
use std::collections::BTreeMap;

// Types

pub struct CodegenEntry {
    pub name: String,
    pub asset_id: u64,
    pub rect_offset: (u32, u32),
    pub rect_size: (u32, u32),
}

/// Recursive tree used for the `nested` codegen style.
enum TreeNode<'a> {
    Leaf(&'a CodegenEntry),
    Branch(BTreeMap<String, TreeNode<'a>>),
}

// Public API

pub fn generate(
    entries: Vec<CodegenEntry>,
    table_name: &str,
    style: &str,
    strip_extension: bool,
    output_path: &str,
) -> Result<()> {
    // Rough pre-allocation: header (3) + ~5 lines per entry + footer (2).
    let mut lines: Vec<String> = Vec::with_capacity(3 + entries.len() * 5 + 2);

    lines.push("-- This file was automatically @generated by Tungsten.".into());
    lines.push("-- It is not intended for manual editing.".into());
    lines.push(String::new());

    match style {
        "nested" => generate_nested(&entries, strip_extension, &mut lines, table_name),
        _ => generate_flat(&entries, strip_extension, &mut lines, table_name),
    }

    lines.push(String::new());
    lines.push(format!("return {}", table_name));

    if let Some(parent) = std::path::Path::new(output_path).parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory for \"{}\"", output_path))?;
    }

    std::fs::write(output_path, lines.join("\n"))
        .with_context(|| format!("Failed to write codegen output to \"{}\"", output_path))
}

// Helpers

#[inline]
fn strip_ext(name: &str) -> &str {
    name.strip_suffix(".png").unwrap_or(name)
}

fn entry_name<'a>(entry: &'a CodegenEntry, strip_extension: bool) -> &'a str {
    if strip_extension {
        strip_ext(&entry.name)
    } else {
        &entry.name
    }
}

// Flat style

fn generate_flat(
    entries: &[CodegenEntry],
    strip_extension: bool,
    lines: &mut Vec<String>,
    table_name: &str,
) {
    lines.push(format!("local {} = {{", table_name));

    for entry in entries {
        let name = entry_name(entry, strip_extension);
        lines.push(format!("\t[\"{}\"] = {{", name));
        lines.push(format!("\t\tImage = \"rbxassetid://{}\",", entry.asset_id));
        lines.push(format!(
            "\t\tImageRectOffset = Vector2.new({}, {}),",
            entry.rect_offset.0, entry.rect_offset.1
        ));
        lines.push(format!(
            "\t\tImageRectSize = Vector2.new({}, {}),",
            entry.rect_size.0, entry.rect_size.1
        ));
        lines.push("\t},".into());
    }

    lines.push("}".into());
}

// Nested style

fn build_tree<'a>(
    entries: &'a [CodegenEntry],
    strip_extension: bool,
) -> BTreeMap<String, TreeNode<'a>> {
    let mut root: BTreeMap<String, TreeNode<'a>> = BTreeMap::new();

    for entry in entries {
        let name = entry_name(entry, strip_extension);
        let parts: Vec<&str> = name.split('/').collect();
        let mut current = &mut root;

        for (i, &part) in parts.iter().enumerate() {
            if i == parts.len() - 1 {
                current.insert(part.to_string(), TreeNode::Leaf(entry));
            } else {
                current = match current
                    .entry(part.to_string())
                    .or_insert_with(|| TreeNode::Branch(BTreeMap::new()))
                {
                    TreeNode::Branch(map) => map,
                    TreeNode::Leaf(_) => break, // path collision — skip
                };
            }
        }
    }

    root
}

fn write_tree(tree: &BTreeMap<String, TreeNode>, lines: &mut Vec<String>, depth: usize) {
    let indent = "\t".repeat(depth);
    let inner_indent = "\t".repeat(depth + 1);

    for (key, node) in tree {
        match node {
            TreeNode::Leaf(entry) => {
                lines.push(format!("{}[\"{}\"] = {{", indent, key));
                lines.push(format!(
                    "{}Image = \"rbxassetid://{}\",",
                    inner_indent, entry.asset_id
                ));
                lines.push(format!(
                    "{}ImageRectOffset = Vector2.new({}, {}),",
                    inner_indent, entry.rect_offset.0, entry.rect_offset.1
                ));
                lines.push(format!(
                    "{}ImageRectSize = Vector2.new({}, {}),",
                    inner_indent, entry.rect_size.0, entry.rect_size.1
                ));
                lines.push(format!("{}}},", indent));
            }
            TreeNode::Branch(subtree) => {
                lines.push(format!("{}[\"{}\"] = {{", indent, key));
                write_tree(subtree, lines, depth + 1);
                lines.push(format!("{}}},", indent));
            }
        }
    }
}

fn generate_nested(
    entries: &[CodegenEntry],
    strip_extension: bool,
    lines: &mut Vec<String>,
    table_name: &str,
) {
    let tree = build_tree(entries, strip_extension);
    lines.push(format!("local {} = {{", table_name));
    write_tree(&tree, lines, 1);
    lines.push("}".into());
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;

    fn dummy_entries() -> Vec<CodegenEntry> {
        vec![
            CodegenEntry {
                name: "48/arrow-up.png".into(),
                asset_id: 12345678,
                rect_offset: (0, 0),
                rect_size: (48, 48),
            },
            CodegenEntry {
                name: "48/arrow-down.png".into(),
                asset_id: 12345678,
                rect_offset: (48, 0),
                rect_size: (48, 48),
            },
            CodegenEntry {
                name: "256/arrow-up.png".into(),
                asset_id: 87654321,
                rect_offset: (0, 0),
                rect_size: (256, 256),
            },
        ]
    }

    #[test]
    fn test_nested_has_subfolders_as_keys() {
        generate(dummy_entries(), "Icons", "nested", true, "test_nested.luau").unwrap();
        let content = std::fs::read_to_string("test_nested.luau").unwrap();
        assert!(content.contains("[\"48\"]"));
        assert!(content.contains("[\"256\"]"));
        assert!(content.contains("[\"arrow-up\"]"));
        std::fs::remove_file("test_nested.luau").unwrap();
    }

    #[test]
    fn test_flat_contains_asset_ids() {
        generate(dummy_entries(), "Icons", "flat", false, "test_flat.luau").unwrap();
        let content = std::fs::read_to_string("test_flat.luau").unwrap();
        assert!(content.contains("rbxassetid://12345678"));
        assert!(content.contains("rbxassetid://87654321"));
        std::fs::remove_file("test_flat.luau").unwrap();
    }

    #[test]
    fn test_strip_extension() {
        generate(dummy_entries(), "Icons", "flat", true, "test_strip.luau").unwrap();
        let content = std::fs::read_to_string("test_strip.luau").unwrap();
        assert!(content.contains("arrow-up"));
        assert!(!content.contains("arrow-up.png"));
        std::fs::remove_file("test_strip.luau").unwrap();
    }
}
