# Originally taken from jackTabsCode/asphalt
# But slightly modified and updated

name: CI

on: push

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --locked --verbose

      - name: Test
        run: cargo test --locked --verbose

  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt

      - name: Clippy
        run: cargo clippy --all-features --all-targets
