# Originally taken from jackTabsCode/asphalt
# But slightly modified and updated

name: CI

on:
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          [
            blacksmith-2vcpu-ubuntu-2404,
            blacksmith-4vcpu-windows-2025,
            blacksmith-6vcpu-macos-latest,
          ]

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: cargo build --locked --verbose

      - name: Test
        run: cargo test --locked --verbose

  lint:
    name: Format & Clippy
    runs-on: blacksmith-4vcpu-ubuntu-2404
    env:
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Rustfmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-features --all-targets
